Change repository type, add liquibase
Toltbcm/book-store pull request #3
Opened 2024-12-30 12:12 UTC by Toltbcm

2025-01-07 10:38 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2025-01-07 10:38 UTC, liliia-ponomarenko commented on src/main/java/org/bookstore/controller/BookController.java
> +public class BookController {
Apply comments from the previous  PR

2025-01-07 10:38 UTC, liliia-ponomarenko commented on src/main/java/org/bookstore/dto/UpdateBookDto.java
> +public class UpdateBookDto {
use the same validators

2025-01-07 10:38 UTC, liliia-ponomarenko commented on src/main/java/org/bookstore/service/impl/BookServiceImpl.java
> +        bookRepository.deleteById(id);
Should you check that the book exists before deleting it?

2025-01-07 14:04 UTC, Toltbcm commented on src/main/java/org/bookstore/dto/UpdateBookDto.java
> +public class UpdateBookDto {
I will do it, but I was thinking about the case where it might be possible to send only the necessary fields.

2025-01-07 14:20 UTC, Toltbcm commented on src/main/java/org/bookstore/service/impl/BookServiceImpl.java
> +        bookRepository.deleteById(id);
Decided not to make an additional request to the database. 
Fixed.

2025-01-15 09:34 UTC, liliia-ponomarenko approved these changes
Good job!

2025-01-15 10:18 UTC, merged